#Configure the location and size of overlay that displays the hovered monitor
#All values are floating point as they are DPI aware
[overlay]
#Top-left corner; Can also be used to move the overlay to a different monitor
position = { x = -1600.0, y = 150.0 }
size = {width = 1280.0, height = 720.0}

#One entry per enabled monitor
[[monitors]]
#DXGI name of the monitor
name = '\\.\DISPLAY1'

#A second monitor
#The overlay key allows for per-monitor overriding of overlay settings

#[[monitors]]
#name = '\\.\DISPLAY2'
#overlay.size = {width = 720.0, height = 1280.0}